#  <h1 align="center" style="color:Brown;"> NAIVE BAYES ML MODEL ON GOLF DATASET </h1> <h3 align="center" style="color:red;">  Sklearn built-in Model</h3>

### READING DATA SET

In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_excel("C:\\Users\\RAPTOR\\Desktop\\golf-dataset-csv.xlsx")
data.head(10)

Outlook  Temp Humidity  Windy Play Golf
0     Rainy   Hot     High  False        No
1     Rainy   Hot     High   True        No
2  Overcast   Hot     High  False       Yes
3     Sunny  Mild     High  False       Yes
4     Sunny   Hot   Normal  False       Yes
5     Sunny  Cool   Normal   True        No
6  Overcast  Cool   Normal   True       Yes
7     Rainy  Mild     High  False        No
8     Rainy  Cool   Normal  False       Yes
9     Sunny  Mild   Normal  False       Yes

### COVERTING STR  VALUES TO ENCODED OBJ FOR MODEL PROCESSING

In [3]:
X = data.iloc[:, [0,1,2,3,4]].values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])
X[:,1] = le.fit_transform(X[:,1])
X[:,2] = le.fit_transform(X[:,2])
X[:,3] = le.fit_transform(X[:,3])
X[:,4] = le.fit_transform(X[:,4])



In [4]:
X

array([[1, 1, 0, 0, 0],
       [1, 1, 0, 1, 0],
       [0, 1, 0, 0, 1],
       [2, 2, 0, 0, 1],
       [2, 1, 1, 0, 1],
       [2, 0, 1, 1, 0],
       [0, 0, 1, 1, 1],
       [1, 2, 0, 0, 0],
       [1, 0, 1, 0, 1],
       [2, 2, 1, 0, 1],
       [1, 2, 1, 0, 1],
       [0, 2, 0, 1, 1],
       [0, 1, 1, 0, 1]], dtype=object)

In [5]:
#data = pd.DataFrame(X,col=['',''])

data = pd.DataFrame(X, columns = ['Outlook','Temp','Humidity','Windy','Play Golf'])


In [6]:
data

Outlook Temp Humidity Windy Play Golf
0        1    1        0     0         0
1        1    1        0     1         0
2        0    1        0     0         1
3        2    2        0     0         1
4        2    1        1     0         1
5        2    0        1     1         0
6        0    0        1     1         1
7        1    2        0     0         0
8        1    0        1     0         1
9        2    2        1     0         1
10       1    2        1     0         1
11       0    2        0     1         1
12       0    1        1     0         1

### CREATING FEATURES & LABEL / FEATURES EXTRACTION

In [7]:
feat = data.drop(['Play Golf'],axis='columns')
feat = feat.to_numpy()

In [8]:
feat

array([[1, 1, 0, 0],
       [1, 1, 0, 1],
       [0, 1, 0, 0],
       [2, 2, 0, 0],
       [2, 1, 1, 0],
       [2, 0, 1, 1],
       [0, 0, 1, 1],
       [1, 2, 0, 0],
       [1, 0, 1, 0],
       [2, 2, 1, 0],
       [1, 2, 1, 0],
       [0, 2, 0, 1],
       [0, 1, 1, 0]], dtype=object)

In [9]:
type(feat)

numpy.ndarray

In [10]:
#label = data.loc[:,["Play Golf"]]
label = data["Play Golf"]

In [11]:
label = label.to_numpy()

In [12]:
type(label)

numpy.ndarray

### SPLITING DATA INTO TRAIN SET AND TEST SET

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(feat,label,test_size=4)

In [14]:
X_train

array([[1, 0, 1, 0],
       [2, 1, 1, 0],
       [2, 2, 0, 0],
       [0, 1, 1, 0],
       [1, 2, 0, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 0],
       [0, 2, 0, 1],
       [1, 1, 0, 1]], dtype=object)

In [15]:
X_test

array([[0, 1, 0, 0],
       [1, 2, 1, 0],
       [2, 2, 1, 0],
       [2, 0, 1, 1]], dtype=object)

In [16]:
type(y_train), y_train.shape

(numpy.ndarray, (9,))

In [17]:
y_train = np.array(y_train, dtype= int)

In [18]:
y_train

array([1, 1, 1, 1, 0, 1, 0, 1, 0])

### TRANING MODEL 

In [19]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)


GaussianNB()

In [20]:
X_test = np.array(X_test, dtype= int)
y_test = np.array(y_test, dtype = int)


### MODEL ACCURACY & RESULTS

In [21]:
model.score(X_test,y_test)

0.75

In [22]:

y_pred = model.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(y_test,y_pred)

In [23]:
print('ACURACY: ', ac)

ACURACY:  0.75


In [24]:
print("Confusion Matrix: \n",confusion_matrix(y_test, y_pred))

Confusion Matrix: 
 [[0 1]
 [0 3]]


In [25]:
X_test,y_test

(array([[0, 1, 0, 0],
        [1, 2, 1, 0],
        [2, 2, 1, 0],
        [2, 0, 1, 1]]),
 array([1, 1, 1, 0]))

In [26]:
y_pred

array([1, 1, 1, 1])

### GETTING RESULT IN TABLE FORM

In [27]:
xt = pd.DataFrame(X_test, columns = ['Outlook','Temp','Humidity','Windy']) #X_train
yt = pd.DataFrame(y_test, columns = ['Play Golf(ACTUAL)'])                  #y_train   
yp = pd.DataFrame(y_pred, columns = ['Play Golf(PREDDICTED)'])              #y_pred

In [28]:
Final = pd.concat([xt,yt,yp],axis='columns')

In [29]:
Final

Outlook  Temp  Humidity  Windy  Play Golf(ACTUAL)  Play Golf(PREDDICTED)
0        0     1         0      0                  1                      1
1        1     2         1      0                  1                      1
2        2     2         1      0                  1                      1
3        2     0         1      1                  0                      1

### TABEL IN ACTUAL FORMAT

In [30]:
def update_OUTLOOK(x):
    for ind,val in enumerate(x):
        if (val==0):
            #print(Final.loc[ind,['Outlook']])
            Final.loc[ind,['Outlook']] = 'Overcast'
        elif(val==1):
            Final.loc[ind,['Outlook']] = 'Rainy'
        elif(val==2):
            Final.loc[ind,['Outlook']] = 'Sunny'

def update_Temp(x):
    for ind,val in enumerate(x):       
        if (val==0):
            Final.loc[ind,['Temp']] = 'Cool'
        elif(val==1):
            Final.loc[ind,['Temp']] = 'Hot'
        elif(val==2):
            Final.loc[ind,['Temp']] = 'Mild' 


def update_Humi(x):
    for ind,val in enumerate(x):
        if (val==0):
            Final.loc[ind,['Humidity']] = 'Normal'
        elif(val==1):
            Final.loc[ind,['Humidity']] = 'High'

def update_windy(x):
    for ind,val in enumerate(x):
        if (val==0):
            Final.loc[ind,['Windy']] = 'False'
        elif(val==1):
            Final.loc[ind,['Windy']] = 'True'


def update_playGolf_pred(x):
    for ind,val in enumerate(x):
        if (val==0):
            Final.loc[ind,['Play Golf(PREDDICTED)']] = 'No'
        elif(val==1):
            Final.loc[ind,['Play Golf(PREDDICTED)']] = 'Yes'
            
def update_playGolf_act(x):
    for ind,val in enumerate(x):
        if (val==0):
            Final.loc[ind,['Play Golf(ACTUAL)']]= 'No'
        if (val==1):
            Final.loc[ind,['Play Golf(ACTUAL)']]= 'Yes'
    
   

In [31]:
update_OUTLOOK(Final['Outlook'])
update_Temp(Final['Temp'])
update_Humi(Final['Humidity'])
update_windy(Final['Windy'])
update_playGolf_act(Final['Play Golf(ACTUAL)'])
update_playGolf_pred(Final['Play Golf(PREDDICTED)'])

In [32]:
Final

Outlook  Temp Humidity  Windy Play Golf(ACTUAL) Play Golf(PREDDICTED)
0  Overcast   Hot   Normal  False               Yes                   Yes
1     Rainy  Mild     High  False               Yes                   Yes
2     Sunny  Mild     High  False               Yes                   Yes
3     Sunny  Cool     High   True                No                   Yes